### ISSUE TITLE
你好！请问一下引入spring-ai-alibaba-starter后影响nacos连接的问题该如何解决？

### ISSUE THREAD

**Issue by evenlai** [alibaba/spring-ai-alibaba#524]
> 可能和spring ai中的nacos适配相关，我们来具体看一下 

 _Originally posted by @chickenlj in [#406](https://github.com/alibaba/spring-ai-alibaba/issues/406#issuecomment-2676059965)_

**Comment by yuluo-yx** [comment]
这里的问题指的是 项目中需要用到 nacos 

但是引入了 ai alibaba 之后，需要排除 nacos 导致了 nacos 不可用的问题吗？

**Comment by paynepang** [comment]
> 这里的问题指的是 项目中需要用到 nacos
> 
> 但是引入了 ai alibaba 之后，需要排除 nacos 导致了 nacos 不可用的问题吗？

单独起一个服务不注入到原项目里面去呢？项目之间使用mcp协议。

**Comment by evenlai** [comment]
这边的需求是在原有的spring-cloud架构的SAAS平台接入spring-ai-alibaba，以便解决Langchain4J对国内模型支持不友好的问题。maven引入spring-ai-alibaba-starter后服务无法再读取nacos配置，只能读取classpath下的配置。在maven中spring-ai-alibaba-starter下排除nacos相关的包也未解决问题。

**Comment by yuluo-yx** [comment]
> > 这里的问题指的是 项目中需要用到 nacos
> > 但是引入了 ai alibaba 之后，需要排除 nacos 导致了 nacos 不可用的问题吗？
> 
> 单独起一个服务不注入到原项目里面去呢？项目之间使用mcp协议。

没有太明白哇

**Comment by yuluo-yx** [comment]
> 这边的需求是在原有的spring-cloud架构的SAAS平台接入spring-ai-alibaba，以便解决Langchain4J对国内模型支持不友好的问题。maven引入spring-ai-alibaba-starter后服务无法再读取nacos配置，只能读取classpath下的配置。在maven中spring-ai-alibaba-starter下排除nacos相关的包也未解决问题。

明白了

**Comment by yuluo-yx** [comment]
> > 这边的需求是在原有的spring-cloud架构的SAAS平台接入spring-ai-alibaba，以便解决Langchain4J对国内模型支持不友好的问题。maven引入spring-ai-alibaba-starter后服务无法再读取nacos配置，只能读取classpath下的配置。在maven中spring-ai-alibaba-starter下排除nacos相关的包也未解决问题。
> 
> 明白了，我试着跟进下看看

**Comment by yuluo-yx** [comment]
hi! 我在本地试着复现了一下，但是没有复现成功，

我的 pom xml 如下：

```xml
<dependencies>
	<dependency>
		<groupId>com.alibaba.cloud.ai</groupId>
		<artifactId>spring-ai-alibaba-starter</artifactId>
		<version>1.0.0-M6.2-SNAPSHOT</version>
		<exclusions>
			<exclusion>
				<artifactId>spring-boot-starter</artifactId>
				<groupId>org.springframework.boot</groupId>
			</exclusion>
		</exclusions>
	</dependency>

	<dependency>
		<groupId>com.alibaba.cloud</groupId>
		<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
		<version>2023.0.3.2</version>
	</dependency>

	<!-- 避免版本不一致，导致 tomcat 启动失败 -->
	<dependency>
		<groupId>com.fasterxml.jackson.core</groupId>
		<artifactId>jackson-databind</artifactId>
		<version>2.15.2</version>
	</dependency>

	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-web</artifactId>
		<version>3.2.4</version>
	</dependency>
</dependencies>
```

applicaiton.yml 如下：

```yml
spring:
  application:
    name: spring-cloud-alibaba-spring-ai-alibaba-naos

  cloud:
    nacos:
      serverAddr: 127.0.0.1:8848
      username: 'nacos'
      password: 'nacos'

  config:
    import:
      - nacos:nacos-config-example.properties?refreshEnabled=true

  ai:
    nacos:
      prompt:
        template:
          enabled: true
```

启动结果：

```text
2025-03-30T16:57:58.807+08:00  INFO 16120 --- [spring-cloud-alibaba-spring-ai-alibaba-naos] [           main] indi.yuluo.Application                   : Started Application in 3.268 seconds (process running for 3.73)
NacosConfigInfo{serverAddr='127.0.0.1:8848', prefix='PREFIX', group='DEFAULT_GROUP', namespace='NAMESPACE1'}
2025-03-30T16:57:58.811+08:00  INFO 16120 --- [spring-cloud-alibaba-spring-ai-alibaba-naos] [           main] c.a.c.n.refresh.NacosContextRefresher    : [Nacos Config] Listening config: dataId=nacos-config-example.properties, group=DEFAULT_GROUP
```

并没有发生错误，也可能是我更新了 spring ai alibaba nacos 相关代码导致的，可以参考这次 pr 的修改再试试呢？
https://github.com/alibaba/spring-ai-alibaba/pull/548
